-  name: "change admin pass"
   shell: "docker exec -ti grafana.1.$(docker service ps -f 'name=grafana.1' grafana -q --no-trunc | head -n1) grafana-cli admin reset-admin-password 4dm1n"


- name: Create influxdb datasource
  grafana_datasource:
    name: "datasource-influxdb"
    grafana_url: "http://{{influxIp2}}:3000"
    grafana_user: "admin"
    grafana_password: "4dm1n"
    ds_type: "influxdb"
    url: "http://{{influxIp2}}:8086"
    database: "test"
    time_interval: ">10s"
    validate_certs: False 


- name: "get dashboards"
  template:
    src: "iterate_dashboards.j2"
    dest: "./roles/igna/defaults/main/grafana.yml"
  run_once: true
  delegate_to: localhost

   
- name: "copiar dashboards"
  uri:
    url: "http://{{influxIp2}}:3000/api/dashboards/db"
    method: POST
    user: admin
    password: 4dm1n
#    body: " {{ lookup('template', 'templates/snmpdashboard.json.j2') }}"
    body: " {{lookup('file', item.file) }} "
    status_code: 200
    body_format: json
    force_basic_auth: yes
    headers: 
       Content-Type: "application/json"
  with_items: 
     - "{{ grafana_dashboards }}"


