  dbrps:
   - { db: "test", rp: "dia"}
  template-id: "basic_template"
  vars: {
    "measurement": {"type" : "string", "value" : "system" },
    "where_filter": {"type": "lambda", "value": "\"host\" == 'target1'"},
    "field": {"type" : "string", "value" : "load1" },
    "warn": {"type" : "lambda", "value" : "\"mean\" < 30.0" },
    "crit": {"type" : "lambda", "value" : "\"mean\" < 10.0" },
    "warnin": {"type" : "string", "value" : "20" },
    "criti": {"type" : "string", "value" : "10" },
    "window": {"type" : "duration", "value" : "1m" },
    "slack_channel": {"type" : "string", "value" : "#test" }
  }

